// <auto-generated />
using LotSystemAdmInfraData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LotSystemAdmInfraData.Migrations
{
    [DbContext(typeof(LotSystemContext))]
    partial class LotSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LotSystemAdmDomain.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomePais")
                        .IsRequired()
                        .HasColumnName("NomePais")
                        .HasColumnType("varchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("SiglaPais")
                        .IsRequired()
                        .HasColumnName("SiglaPais")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3);

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
